// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BigCardController from "./big_card_controller"
application.register("big-card", BigCardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
